[package]
name = "resque-web"
version = "0.1.0"
authors = ["mh039333 <mike.harris@cerner.com>"]
edition = "2018"

[dependencies]
redis = "0.11.0-beta.1"
actix-web = "1.0.3"
actix-files = "0.1.1"
serde = "1.0.94"
serde_json = "1.0.40"
serde_derive = "1.0.94"
env_logger = "0.6.2"
plugin_manager = { path = "plugin_manager", version = "0.1.0" }